const Express = require('express');
const App = Express();
const EmpresaRuta = require('./Rutas/EmpresaRuta');
const EmpresaPortadaRuta = require('./Rutas/EmpresaPortadaRuta');
const ModelosTypescriptRuta = require("./Rutas/ModelosTypescriptRuta");
const SubirImagenRuta = require("./Rutas/SubirImagenRuta");
const UsuarioRuta = require("./Rutas/UsuarioRuta");
const RolRuta = require("./Rutas/RolRuta");
const PermisoRuta = require("./Rutas/PermisoRuta");
const PermisoRolRecursoRuta = require("./Rutas/PermisoRolRecursoRuta");
const RecursoRuta = require("./Rutas/RecursoRuta");
const NavbarRuta = require("./Rutas/NavbarRuta");
const LogoRuta = require("./Rutas/LogoRuta");
const LogoImagenRuta = require("./Rutas/LogoImagenRuta");
const MenuPortadaRuta = require("./Rutas/MenuPortadaRuta");
const CarruselRuta = require("./Rutas/CarruselRuta");
const CarruselImagenRuta = require("./Rutas/CarruselImagenRuta");
const FooterRuta = require("./Rutas/FooterRuta");
const RedSocialRuta = require("./Rutas/RedSocialRuta");
const RedSocialImagenRuta = require("./Rutas/RedSocialImagenRuta");
const ClasificacionProductoRuta = require("./Rutas/ClasificacionProductoRuta");
const IconoRuta = require("./Rutas/IconoRuta");
const OtroRuta = require("./Rutas/OtroRuta");
const ProductoRuta = require("./Rutas/ProductoRuta");
const CarritoPortadaRuta = require("./Rutas/CarritoPortadaRuta");
const ReporteProductoRuta = require("./Rutas/ReporteProductoRuta");
const ReporteRedSocialRuta = require("./Rutas/ReporteRedSocialRuta");
const ReporteTiempoPaginaRuta = require("./Rutas/ReporteTiempoPaginaRuta");
const ReporteVistaRuta = require("./Rutas/ReporteVistaRuta");
const ContactanosPortadaRuta = require("./Rutas/ContactanosPortadaRuta");
const ProductoPortadaRuta = require("./Rutas/ProductoPortadaRuta");
const LoginPortadaRuta = require("./Rutas/LoginPortadaRuta");
const PortadaOtroRuta = require("./Rutas/PortadaOtroRuta");
const PermisosTablasDisponibles = require("./Rutas/PermisosTablasDisponiblesRuta");
const Pago = require("./Rutas/PagoRuta");
const ResumenGeneralPago = require("./Rutas/EstadoTecnicoEmpresaRuta");

const Login = require("./Rutas/LoginRuta");
const Ruter = 'api';
const CuerpoJson = require('./FuncionIntermedia/CuerpoJson');
const CuerpoUrlCodificado = require('./FuncionIntermedia/CuerpoUrlCodificado');
const { ConfiguracionCors } = require('./FuncionIntermedia/Cors');

App.use(Express.text({ type: 'text/plain' }));
App.use(ConfiguracionCors());
App.use(CuerpoJson);
App.use(CuerpoUrlCodificado);

App.use(`/${Ruter}`, EmpresaRuta);
App.use(`/${Ruter}`, EmpresaPortadaRuta);
App.use(`/${Ruter}`, UsuarioRuta);
App.use(`/${Ruter}`, RolRuta);
App.use(`/${Ruter}`, PermisoRuta);
App.use(`/${Ruter}`, PermisoRolRecursoRuta);
App.use(`/${Ruter}`, RecursoRuta);
App.use(`/${Ruter}`, NavbarRuta);
App.use(`/${Ruter}`, LogoRuta);
App.use(`/${Ruter}`, LogoImagenRuta);
App.use(`/${Ruter}`, MenuPortadaRuta);
App.use(`/${Ruter}`, CarruselRuta);
App.use(`/${Ruter}`, CarruselImagenRuta);
App.use(`/${Ruter}`, FooterRuta);
App.use(`/${Ruter}`, RedSocialRuta);
App.use(`/${Ruter}`, RedSocialImagenRuta);
App.use(`/${Ruter}`, ClasificacionProductoRuta);
App.use(`/${Ruter}`, IconoRuta);
App.use(`/${Ruter}`, OtroRuta);
App.use(`/${Ruter}`, ProductoRuta);
App.use(`/${Ruter}`, CarritoPortadaRuta);
App.use(`/${Ruter}`, ReporteProductoRuta);
App.use(`/${Ruter}`, ReporteRedSocialRuta);
App.use(`/${Ruter}`, ReporteTiempoPaginaRuta);
App.use(`/${Ruter}`, ReporteVistaRuta);
App.use(`/${Ruter}`, ContactanosPortadaRuta);
App.use(`/${Ruter}`, ProductoPortadaRuta);
App.use(`/${Ruter}`, LoginPortadaRuta);
App.use(`/${Ruter}`, PortadaOtroRuta);
App.use(`/${Ruter}`, PermisosTablasDisponibles);
App.use(`/${Ruter}`, Pago);
App.use(`/${Ruter}`, ResumenGeneralPago);

App.use(`/${Ruter}`, ModelosTypescriptRuta);
App.use(`/${Ruter}`, SubirImagenRuta);
App.use(`/${Ruter}`, Login);

module.exports = App;